language: ruby
cache: bundler
rvm:
  - 2.1.1
before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc' # skip installing docs for gems
bundler_args: --without production development staging deploy
before_script:
  - RAILS_ENV=test bundle exec rake db:setup
script:
  - "bundle exec rspec spec"
